config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:new, :create, :show] do 
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses

    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    
    validates :name, uniqueness: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :set_cocktail, only: [:show]

    def index
        @cocktails = Cocktail.all
    end

    def new
        @cocktail = Cocktail.new
    end

    

    def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
        else
            render "new"
        end
    end

    def show
        @cocktail = Cocktail.find(params[:id])
    end

    private
    def set_cocktail
        @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
        params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_cocktail, only: [:new, :create]

    def new
        @dose = Dose.new
    end

    def create
        @dose = Dose.new(dose_params)
        @dose.cocktail = @cocktail

        if @dose.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy

        redirect_to cocktail_path(@dose.cocktail.id)
    end


    private

    def find_cocktail
        @cocktail = Cocktail.find(params[:cocktail_id])
    end
    

    def dose_params
        params.require(:dose).permit(:description, :coctail_id, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="navbar">
  <h1>Cocktails</h1>  
  <div>
    <i class="fas fa-cocktail"></i>
  </div>
</div>

<div class="banner">
  <div class="banner_text">
    <h1>Classic Cocktails You Must Know How To Make</h1>
  </div>
</div>

<div>
  <table>
    <thead>
      <tr>
        <th>List of cocktails: <i class="fas fa-cocktail"></i> </th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @cocktails.each do |cocktail| %>
        <tr class="card">
          <td><%= link_to cocktail.name, cocktail_path(cocktail.id) %></td>
          <td><%= link_to 'Add dose', new_cocktail_dose_path(cocktail) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="btn btn-secondary btn-lg btn-block">
  <%= link_to 'Create new cocktail', new_cocktail_path %>
  </div>
  
  
  
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail list</h1>

<%= simple_form_for([@cocktail]) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to all cocktails', root_path %>

app/views/cocktails/show.html.erb
<p>
  <strong>Name of the coctail:</strong>
  <%= @cocktail.name %>
  

    
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.description %>
        <%= dose.ingredient.name %>
        <%= link_to "Delete", dose_path(dose.id), method: :delete, class: 'btn btn-primary' %>
      </li>
    <% end %>
  </ul>
  
  
</p>



<%= link_to "Go back", root_path, class: 'btn btn-primary' %>

app/views/doses/new.html.erb
<h1>Adding dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>

  <%= f.submit class: 'btn btn-primary' %>
 
<% end %>

<%= link_to 'Back to all cocktails', root_path %>

<%# <div class="card-tags">
    <% @dose.cocktail_id.each do |dose| %>
        <%# <span><%= link_to cocktail_doses.x.description, cocktail_doses_path(x), method: :delete %></span>
    <%# <% end %> 
<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>